use ro_prod_dsstox;
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "(-)-quinuclidinyl benzylate";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "(es)citalopram";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "(R)-3-(piperidin-4-ylmethoxy)-4- ((tetrahydrofuran-3-yl)oxy)benzo[d]isoxazole (M1)";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "(R)-7-cyano-N-(quinuclidin-3-yl)benzo[b]thiophene-2-carboxamide";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "(R)-7-fluoro-N-(quinuclidin-3-yl)benzo[b]thiophene-2-carboxamide";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "(S)-[5-3H]nicotine";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "1'-hydroxyapiol";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "1'-hydroxyestragole glucuronide";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "1'-hydroxymethyleugenol glucuronide";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "1'-hydroxymyristicin";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "1'-hydroxymyristicin glucuronide";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "1'-hydroxysafrole glucuronide";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "1'-oxomethyleugenol";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "1'-oxomyristicin";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "1'-sulfooxyestragole";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "1'-sulfooxymethyleugenol";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "1'-sulfoxymyristicin";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "1,1'-trimethylenebis{4-hydroximinomethyl}pyridinium dibromide";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "1,1,1-trihaloethane";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "1,1,2,2-perchloroethylene";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "1,16-diol-patupilone acid";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "1,2,3,4,6,7,8-heptachlorodibenzo-p-furan";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "1,2,3,4,7,8-hexachlorodibenzo-p-furan";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "1,2,3,6,7,8-hexachlorodibenzo-p-furan";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "1,2,3,7,8,9-hexachlorodibenzo-p-furan";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "1,2,3,7,8-pentachlorodibenzo-p-furan";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "1,2-dichloroethane GSH conjugate metabolite";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "1,2-dichloroethane oxidative metabolite";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "1,2-dichlorovinylcysteine";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "1,2-epoxy-butene-3";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "1,2-epoxybut-3-ene GSH-conjugate";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "1,2:3,4-diepoxybutane GSH-conjugate";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "1,4-bisdesoxycyadox";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "1,4-bisdesoxymequindox";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "1-hydroxy-midazolam glucuronide";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "1-naphthylenyl methylcarbamate";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "1-pyrenylglucuronide";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "125I-beta-endorphin";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "13C-erythromycin";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "13C-uracil";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "13CO2";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "14C-erythromycin";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "14CO2";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "17β-estradiol";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "17beta-estradiol";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "1h8-toluene";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "2' ,3' -dihydroxyapiol";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "2',3'-dihydroxymyristicin";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "2',3'-dihydroxysafrole";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "2',3,4,4',5-pentachlorobiphenyl";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "2(e)-ene-valproic acid";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "2,2',3,4,4',5'-hexachlorobiphenyl";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "2,2',3,4,4',5,5'-heptachlorobiphenyl";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "2,2',4,4',5,5'-hexachlorobiphenyl";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "2,3,5-dimethylbenzoic acid";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "2,3,7,8-tetrachlorodibenzo-p-furan";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "2,3,7,8-tetrachlorodibenzo-para-dioxin";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "2,3,7,8-tetrachlorodibenzodioxin";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "2,6-dichloro-4-(3,3-dichloroallyloxy)phenyl 3-[5-(trifluoromethyl)-2-pyridyloxy]propyl ether";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "2-amino-2[2-(-4-octylphenyl)ethyl]propane-1,3-diol hydrochloride";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "2-chloro-4-amino-6-isopropylamino-1,3,5-triazine";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "2-chloro-4-ethylamino-6-amino-1,3,5-triazine";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "2-chloro-n-(4-chloro-3-(pyridine-2-yl)phenyl)-4-(methylsulfonyl)benzamide";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "2-hydroxy-4,5-dimethoxy-allylbenzene";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "2-hydroxy-atorvastatin acid";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "2-hydroxymelengestrol acetate";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "2-methylbenzoylglycine";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "2-[1-Hexyloxyethyl]-2-devinyl pyropheophorbide-a";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "2-[4-(3-quinolin-6-ylmethyl-3H- [1,2,3]triazolo[4,5-b]pyrazin-5-yl)-pyrazol-1-yl]-ethanol";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "25-hydroxyvitamin D";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "3'-hydroxymyristicin";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "3,3',4,4',5'-pentachlorobiphenyl";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "3,3',4,4',5-pentachlorobiphenyl";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "3,5,5-trichloropyridinol";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "3-hydroxy-4-methoxyallylbenzene";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "3beta-glucuronide metabolite of morphine";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "4'OH- phenoxybenzoic acid";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "4-allyl-3,6- dimethoxybenzene-1,2-diol";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "4-ene-valproic acid";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "4-hydroxy-3GS-coumarine";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "4-methylbenzoylglycine";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "4-n-acetyl-2-amino toluene";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "4-o-(2-hydroxy-[1,2-3H]ethyl)-rapamycin";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "5,5'- dimethyloxazolidine-2,4-dione";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "5-allyl-2,3-dihydroxyanisole";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "5-ethyl-5-heptyl barbituric acid";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "5-ethyl-5-octyl barbituric acid";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "5-ethyl-5-propyl barbituric acid";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "5-hydroxy mono-(2-ethylhexyl) phthalate";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "5-hydroxy-pomalidomide";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "6-hydroxymethylmelengestrol acetate";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "7-(((4-(((R)-tetrahydrofuran-3-yl)oxy)benzo [d]isoxazol-3-yl)oxy)methyl)octahydro-3H (M2)";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "7-ethyoxycoumarin";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "7-GS-DHP";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "7E3";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "7E3 antibody";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "8C2";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "99m technetium-mebrofenin";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "99m-technetium-labelled carbon nanoparticles";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "AB-01";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "AB-02";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "ACAPHA";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "ACP-5862";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "acrylamide glutathione conjugates";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "acyl-b-D glucuronide metabolite";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "Adalimumab";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "aglycone";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "albumin-binding dAbs";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "alpha-zearalanol glucuronide";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "alpha-zearalenol glucuronide";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "aminophen-sulfate";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "anti-FcRn monoclonal antibodies";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "anti-FcRn monoclonal antibody";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "anti-IL-17 IgG";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "anti-lymphocyte globulin";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "antibody-conjugated monomethyl auristatin E";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "apicidin";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "arlevert";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "arsenate";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "arsenite";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "asunercept";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "AZD1305";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "B1A10-2474";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "BAY 79-4620";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "BDE-188";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "belimumab";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "benzene glycol";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "benzenetriol conjugates";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "beta-zearalanol glucuronide";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "beta-zearalenol glucuronide";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "bevacizumab";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "BFA F(ab')2";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "bile acid";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "bisphenol A bis(2,3-dihydroxypropyl) glycidyl ether";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "bisphenol A sulfation metabolites";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "blinatumomab";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "BMS-69051";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "BPA glucuronide";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "BPA sulfate";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "brentuximab vedotin";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "bromodichloromethane CYP1A2 metabolite";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "bromodichloromethane CYP2A6 metabolite";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "bromodichloromethane CYP2B1 metabolite";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "bromodichloromethane CYP2B6 metabolite";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "bromodichloromethane CYP2C11 metabolite";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "bromodichloromethane CYP2D6 metabolite";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "bromodichloromethane CYP2E1 metabolite";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "bromodichloromethane CYP3A1 metabolite";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "bromodichloromethane CYP3A4 metabolite";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "buagafuran";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "butadiene diepoxide GSH conjugates";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "butadiene monoepoxide GSH conjugates";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "butene diol metabolized by alcohol dehydrogenase";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "butenediol";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "butoxyethanol glucuronide";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "butoxyethanol-glucuronide";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "canakinumab";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "capreomycin";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "carbon";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "carboxyhemoglobin";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "carboxylosartan";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "caspofungin";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "catechol conjugates";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "CDA1";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "chloroethane glutathione conjugate";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "chloroethylene epoxide";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "chloroform metabolite";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "chloromethyl glutathione";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "ciazepam";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "cis glucuronide of 4-hydroxytamoxifen";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "cis sulfate of 4-hydroxytamoxifen";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "cis-3-(2,2 dichlorovinyl)- 2,2-dimethyl-(1-cyclopropane) carboxylic acid";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "cis-permethrins";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "CK2.3";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "clonidine-3H hydrochloride";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "clopi-H4";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "colistin methanesulfonate";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "conjugates: 2-methoxy-1-propionic acid,PGME-Gluc,PGME-SO4,1-methoxy-2-propanol";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "covalently bound 1,2-dichlorobenzene metabolites";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "covalently bound naphthalene metabolites";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "cyclosporine metabolite AM1";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "CYP1A2 (8-OH) from efavirenz";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "CYP1A2 metabolite of clonidine";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "CYP1A2 metabolite of paroxetine";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "CYP1A2 metabolites of efavirenz";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "CYP2A6 (7-OH) from efavirenz";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "CYP2A6 (8-OH) from efavirenz";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "CYP2A6 metabolites of efavirenz";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "CYP2B6";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "CYP2B6 metabolites of efavirenz";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "CYP2B6*1/*1 (7-OH) from efavirenz";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "CYP2B6*1/*1 (8-OH) from efavirenz";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "CYP2B6*1/*6 (7-OH) from efavirenz";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "CYP2B6*1/*6 (8-OH) from efavirenz";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "CYP2B6*6/*6 (7-OH) from efavirenz";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "CYP2B6*6/*6 (8-OH) from efavirenz";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "CYP2B6.1 (8-OH) from efavirenz";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "CYP2B6.6 (8-OH) from efavirenz";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "CYP2C19";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "CYP2C19 metabolite of voriconazole";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "CYP2C8 metabolite of norverapamil";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "CYP2C9";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "CYP2C9 metabolite of paroxetine";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "CYP2C9 tamoxifen";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "CYP2D6";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "CYP2D6 metabolite of clonidine";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "CYP2D6 metabolite of paroxetine";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "CYP2D6 tamoxifen";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "CYP2E1 and GST metabolites of bromochloromethane";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "CYP2E1 metabolite of paracetamol";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "CYP3A from carbamazepine";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "CYP3A from phenobarbital";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "CYP3A from rifampin";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "CYP3A metabolite of clonidine";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "CYP3A4";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "CYP3A4 (8-OH) from efavirenz";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "CYP3A4 metabolite of norverapamil";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "CYP3A4 metabolite of paroxetine";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "CYP3A4 metabolite of voriconazole (1)";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "CYP3A4 metabolite of voriconazole (2)";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "CYP3A4 metabolites of efavirenz";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "CYP3A5";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "CYP3A5 (8-OH) from efavirenz";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "CYP3A5 metabolite of norverapamil";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "CYP3A5 metabolite of paroxetine";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "CYP3A5 metabolites of efavirenz";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "CYP450 metabolite of rhein";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "cytochrome P450 3A4";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "cytochrome P450 metabolites of deltamethrin";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "dAb2 (domain antibodies)";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "dabigatran 1-0-acylglucuronide";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "dabigatran etexilate";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "dacetuzumab";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "daidzen";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "dearylated metabolites of chlorpyrifos (trichloropyridinol and diethylthiophosphate)";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "dearylation metabolite of chlorpyrifos";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "desulfurated metabolites of chlorpyrifos";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "dextrorphan-0-glucuronide";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "di-digitosoxide";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "diaminochlorotriazine";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "dibenzo[def,p]chrysene diols";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "dibenzo[def,p]chrysene triols";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "dichloroethane";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "dichloromethane cytochrome P450 metabolite";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "dichloromethane glutathione metabolite";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "dichloromethane GST metabolites";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "dichloromethane GSTT1 metabolite";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "dichloromethane MFO metabolite";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "dichloromethane p450 metabolites";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "dichlorovinyl glutathione";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "dichlorovinylcysteine";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "dichlorovinylglutathione";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "dideoxyquinocetone";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "digoxin-Fab";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "dihydroxymelengestrol acetate";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "diisopropyfluorophosphate";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "diisopropylfluorophosphoric acid";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "dimethyl arsenic";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "dimethyl arsinate";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "dimethylarsenate";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "dimethylarsinic acid (V)";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "dioxins";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "domain antibody dAb2";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "double CYP2E1 binding metabolite of bromochloromethane";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "DSTA4637A";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "E-3' -N2 - dGuo";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "E-3'-N2-dGuo adduct";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "efalizumab";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "endogenous IgC";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "endosulfan metabolites";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "epithelial lining fluid";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "epoxybutane diol";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "epoxybutane diol GSH conjugates";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "epoxybutene GSH conjugate";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "erlizumab";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "estradiol 17beta-d-glucuronide";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "estradiol 3-sulfate-17beta-d-glucuronide";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "etanercept";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "ethandioyl dichloride";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "ethoxybenzamide";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "ethyl acrylate-NPSH";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "ethylglycol acetate";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "F(ab')2";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "Fab";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "FC-113";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "FcRn WT";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "FcRn-";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "G2917";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "gasoline";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "gasoline summer blend (percent components by weight included)";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "gasoline winter blend (percent components by weight included)";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "gemfibrozil 1-O-β glucuronide";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "gemfibrozil 1-O-β-glucuronide";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "gemfibrozil 1-O-beta glucuronide";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "gemfibrozil 1-O-beta-glucuronide";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "genistein conjugates";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "genistein-40,7-O-diglucuronide";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "genistein-40-O-glucuronide";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "genistein-40-O-glucuronide-7-O-sulfate";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "genistein-40-O-sulfate";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "genistein-7-O-glucuronide-40- O-sulfate";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "genistein-7-O-sulfate";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "glucagon";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "glucocorticoid-induced leucine zipper";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "glucuronide";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "glutathione conjugates of 1,2-dichlorobenzene";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "glutathione conjugates of chloroacetaldehyde";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "glutathione conjugates of chloroethylene epoxide";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "glutathione ethyl acrylate";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "glycidamide glutathione conjugates";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "glyoxylate";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "gold nanoparticles";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "grapefruit juice";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "GSH metabolites";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "GST metabolites";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "GST pathway metabolite";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "hesperetin-3' -O-glucuronide";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "hesperetin-3' -O-sulfate";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "hesperetin-3',7-O-diglucuronide";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "hesperetin-7- O-sulfate";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "hesperetin-7-O-glucuronide";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "hesperetin-O-monoglucuronide-O-monosulfate";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "hexachloro-1,3-butadiene cysteine conjugate";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "hexachloro-1,3-butadiene glutathione conjugate";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "hexachloro-1,3-butadiene n-acetylcysteine conjugate";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "HO-D5";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "hydrolysis metabolite of chlorpyrifos-oxon";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "hydrolyzed 1,2-epoxy-3-butene";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "hydroquinone conjugates";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "hydroquinone cysteine";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "hydroquinone cysteine conjugate";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "hydroquinone di-glutathione conjugate";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "hydroquinone glutathione";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "hydroquinone glutathione conjugate";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "hydroquinone mono-glutathione conjugate";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "hydroquinone n-acetylcystein conjugate";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "hydroxy molinate";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "hydroxy tebuconazole";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "hydroxyl-itraconazole";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "IL-6";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "immune globulin";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "immunoglobulin";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "interferon alpha";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "inulin";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "ionic silver";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "iron oxide nanoparticles";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "ISIS 1082 (5'GCC GAG GTC CAT GTC GTA CGC-3')";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "isoetretin";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "isotopic propanol";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "KNI-272";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "levo-alpha-acetyl-methadol";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "liver carboxylesterase metabolite of deltamethrin";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "liver carboxylesterase metabolites of deltamethrin";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "lumped component of gasoline";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "M1";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "M2";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "m8";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "mAb 7E3";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "MED18897";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "MEDI-524";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "MeIQx-M1";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "meta-hydroxydichlorodiphenylsulfone";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "meta-hydroxydichlorodiphenylsulfone glucuronide";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "methyl hippuric acid";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "methyl tert-butyl ether CYP2A6 metabolite";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "methyl tert-butyl ether CYP2E1 metabolite";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "methylene chloride GST metabolite";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "methylene chloride MFO metabolite";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "methyleugenol-2',3'-oxide";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "metoprolol alpha-OH by CYP2D6";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "metoprolol alpha-OH by CYP3A4";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "metoprolol O-demethylation by CYP2D6";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "metoprolol O-demethylation by CYP3A4";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "MFO metabolites";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "MFO pathway metabolite";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "molinate glutathione";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "mono(2-ethylhexyl) phthalate conjugates";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "mono(2-ethylhexyl)phthalate 0-glucuronide";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "mono(n-butyl) phthalate";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "monobutyl phthalate conjugates";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "monobutyl phthalate glucuronide";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "monoclonal antibodies";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "monoclonal antibodies CD11a";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "monoclonal antibody CC49";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "monoclonal antibody IgGl (ZCE025)";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "monohydroxymelengestrol acetate";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "monomethyl arsenic";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "monomethyl arsonate";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "monomethyl auristatin E";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "monomethylarsenate";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "monomethylarsenic";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "morphine 3-beta-glucuronide metabolite";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "Motavizumab";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "n-acetyl dichlorovinylcysteine";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "N-acetyl-para- aminophenol glucuronide";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "N-acetyl-para- aminophenol sulfate";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "n-acetyldichlorovinylcysteine";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "N2-(trans-isoestragole-3'-yl)-2'- deoxyguanosine";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "N2-(trans-isoestragole-3'-yl)-2'-deoxyguanosine";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "N4-acetyl metabolite of sulfamethazine";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "naphthalene 1R,2S-oxide";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "naphthalene 1S,2R-oxide";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "naphthalene oxide";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "naphthalene oxide dihydrodiols";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "naphthalene oxide GSH conjugates";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "nevadensin glucuronide";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "nevadensin sulfonate";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "nitrogen";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "nonylphenol";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "NVS123";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "O-desmethyl CC-223";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "octachlorodibenzo-p-furan";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "other hydroxylated metabolites of carbaryl";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "oxidative metabolites of trichloroethylene (TCA,DCA,TCOH)";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "p,p'-dichlorodiphenylsulfone";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "p-glycoprotein";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "p-methylketophenol";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "P450 metabolite of deltamethrin";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "patupilone acid";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "PEG-40 conjugated peptide";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "pegylated polyacrylamid nanoparticles";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "pentachlorobutadiene cysteine conjugate";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "perfluorooctanoate sulfonate";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "phase II metabolites of bisphenol a";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "phenol conjugates";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "phenyl conjugates";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "phenylmercapturic acid conjugates";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "phenytoin ethanolamine";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "phenytoin ethylenediamine";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "phenytoin piperazine";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "phenytoin piperidine";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "phosphorothioate oligonucleotide";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "plasma carboxylesterase metabolite of deltamethrin";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "plasma carboxylesterase metabolites of deltamethrin";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "polyacrylamide nanoparticles";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "polybrominated diphenyl ether";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "polyethylene glycol-coated polyacrylamide nanoparticles";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "Polyphenon E";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "posaconazole";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "pralmorelin hydrochloride";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "PSC-833";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "purine-6-sulfonate";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "QD705";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "quercetin diconjugates";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "quercetin glucuronides";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "quercetin methylates";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "quercetin monoconjugates";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "quercetin sulfates";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "quercetin triconjugates";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "quercetin-3'-o-sulfate";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "quercetin-7-o-glucuronide";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "quercetin-7-o-sulfate";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "R,S)-1-{2-[2-(3-methoxyphenyl)ethyl]-phenoxy}- 3-(dimethylamino)-2-propanol (M-1)";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "R-95913";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "R-moxalactam";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "R-tebuconazole";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "rhTNF-a";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "rilotumumab";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "ritalinic acid";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "RSHZ19";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "s-(2-hydroxyethyl)mercapturic acid";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "S-8";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "S-moxalactam";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "S-tebuconazole";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "S-verapamil";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "s-[2-(n7-guanyl)ethyl]mercapturic acid";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "S-[3-(1-oxohexyl)] glutathione";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "s-[3-(1-oxohexyl)]-glutathione";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "SB249417";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "serum creatinine";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "sex hormone binding globulin";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "silver nanoparticle";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "silver nanoparticles";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "silybin a+A205";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "SN-38";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "sodium 5-(1,1-dioxothiazinan-2-yl)-N-((4-fluorophenyl)methyl)-8-hydroxy-1,6-naphthyridine-7-carboxamide)";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "sodium arsenate";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "spinosad";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "sulfation metabolite of bisphenol A";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "sulfation metabolite of paracetamol";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "sulfation metabolites of morphine";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "SULT metabolite of rhein";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "SUN5555";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "SX (phase I compound,no structure)";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "T cells";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "T84.66";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "T84.66 anti-CEA mAb";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "TAK-357";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "tamoxifen-n-glucuronide";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "tebuconazole";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "tefibazumab";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "tetrachlorobenzyltoluene 87";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "tetrachlorobenzyltoluene 88";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "tetrachlorobenzyltoluene 94";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "tetrachlorodibenzo-p-dioxin";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "tetrachloroethylene-Fe-O intermediate";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "tetramer-diol of octamethylcyclotetrasiloxane";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "thiodiacetic sulfoxide";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "thiopurine methyltransferase";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "titanium dioxide nanoparticles";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "TPN729MA";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "trans glucuronide of 4-hydroxytamoxifen";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "trans sulfate of 4-hydroxytamoxifen";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "trans-3'-hydroxycotinine";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "trans-3'-hydroxycotinine glucuronide";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "trans-3-(2,2 dichlorovinyl)- 2,2-dimethyl-(1-cyclopropane) carboxylic acid";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "trans-DCE";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "trans-permethrins";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "Trastuzumab";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "trebananib";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "trichloroethanol bound to glucuronide (not trichloroethanol glucuronide)";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "trichloroethylene metabolites";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "trichloropyridinol";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "trichlorovinyl cysteine";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "trimethyluric acid";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "UGT metabolite of rhein";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "UGT1A6 metabolite of paracetamol";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "UGT2B7 metabolites of efavirenz";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "UGT2B7 metabolites of morphine";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "UK-343,664";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "unlabeled anti-CD45 antibodies";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "white spirit";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "x-hexane";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "xylene";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "YH4808";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "Z-GP-doxorubicin";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "ZCE F(ab')2";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "ZCE Fab";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "ZCE IgG";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "ZCEO25 IgG";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "zearalanone glucuronide";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "zearalenone glucuronide";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "zinc oxide nanoparticles";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "zoptarelin doxorubicin";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "[125I]-2-Iodo-3,7,8-tetrachlorodibenzo-p-dioxin";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "[14C]cobimetinib";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "[2H2]-dichloromethane";
select b.casrn from other_casrns b, synonyms a where a.fk_generic_substance_id = b.fk_generic_substance_id and a.identifier = "[2H]dichloromethane";
